host = "127.0.0.1"
port = 4214
pool_size = 1
read_pool_size = 1
write_pool_size = 1
# pool_size = 10
# read_pool_size = 10
# write_pool_size = 2
enable_writes = true
ducklake_enable = true
ducklake_init_sql = """
    -- Install required extensions
    INSTALL ducklake;
    LOAD ducklake;
    INSTALL postgres;
    LOAD postgres;

    -- Attach your own table
    -- Export the secrets in the environment variables
    -- S3 or R2: https://duckdb.org/docs/stable/core_extensions/httpfs/s3api
    -- Postgres: https://duckdb.org/docs/stable/core_extensions/postgres#configuration
    -- ATTACH 'ducklake:postgres:dbname=ducklake-test' AS swandb (DATA_PATH 'r2://ducklake-test/');

    -- Start the UI server at http://localhost:4213/
    call start_ui_server();

    ATTACH IF NOT EXISTS 'ducklake:postgres:dbname=ducklake-test' AS swandb (DATA_PATH 'r2://ducklake-test/');

    CREATE OR REPLACE TABLE swandb.person (
        first_name VARCHAR,
        last_name VARCHAR,
        email VARCHAR
    );

    CREATE OR REPLACE TABLE swandb.place (
        country VARCHAR,
        city VARCHAR NULL,
        telcode INTEGER
    );

    use swandb;
"""
